version: '3'

services: 
  app:
    build: ./app
    ports:
      - "3000:3000"
    # volumes:
    #   # map local to remote folder, exclude node_modules
    #   - ./$LOCAL_FOLDER:/$CONTAINER_FOLDER
    #   - /$CONTAINER_FOLDER/node_modules
    # LOCAL_FOLDER = ./app
    # CONTAINER_FOLDER = /usr/src/app
    volumes: 
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
        
    restart: always
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
