FROM node:lts

# WORKDIR /$CONTAINER_FOLDER
WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

RUN npm i -g nodemon

COPY . .

EXPOSE 3000

# CMD ["npm", "start"]
CMD ["npm", "run", "start:watch"]